name: FigmaiOS
options:
  minimumXcodeGenVersion: 2.37.0
  deploymentTarget:
    iOS: "16.0"
targets:
  FigmaiOS:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: App
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourcompany.figmaios
        DEVELOPMENT_TEAM: ""
        SWIFT_VERSION: 5.0
        INFOPLIST_FILE: App/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    scheme:
      testTargets: []

